version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: local-Dockerfile
    container_name: local_crowd_app
    restart: always
    working_dir: /var/www/html
    ports:
      - "8881:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: local-crowd-app
      APP_ENV: development
      APP_KEY: base64:f6S4kacQranFolBU+4y4sFv/Nh1tz7bJZwjyINWNYOw=
      APP_DEBUG: "true"
      APP_TIMEZONE: UTC
      APP_URL: http://localhost:8881
      
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: dbpass123456
      
      MAIL_MAILER: smtp
      MAIL_HOST: local.host
      MAIL_PORT: 587
      MAIL_USERNAME: user@example.com
      MAIL_PASSWORD: 123pass456
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: user@example.com
      MAIL_FROM_NAME: laravel-local
    networks:
      - app_network
      
    command: >
      bash -c "php artisan migrate --force && php artisan storage:link && apache2-foreground"

  mysql:
    image: mysql:5.7
    container_name: local_crowd_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpass123456
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: dbpass123456
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: local_crowd_phpmyadmin
    restart: always
    ports:
      - "8890:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: dbpass123456
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
