name: Build and Deploy

on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Portainer Secrets
        id: portainer_secrets
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "PORTAINER_URL=${{ secrets.PROD_PORTAINER_URL }}" >> $GITHUB_ENV
            echo "PORTAINER_TOKEN=${{ secrets.PROD_PORTAINER_TOKEN }}" >> $GITHUB_ENV
            echo "STACK_ID=${{ secrets.PROD_STACK_ID }}" >> $GITHUB_ENV
            echo "ENDPOINT_ID=${{ secrets.PROD_ENDPOINT_ID }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "PORTAINER_URL=${{ secrets.STAGING_PORTAINER_URL }}" >> $GITHUB_ENV
            echo "PORTAINER_TOKEN=${{ secrets.STAGING_PORTAINER_TOKEN }}" >> $GITHUB_ENV
            echo "STACK_ID=${{ secrets.STAGING_STACK_ID }}" >> $GITHUB_ENV
            echo "ENDPOINT_ID=${{ secrets.STAGING_ENDPOINT_ID }}" >> $GITHUB_ENV
          else
            echo "PORTAINER_URL=${{ secrets.DEV_PORTAINER_URL }}" >> $GITHUB_ENV
            echo "PORTAINER_TOKEN=${{ secrets.DEV_PORTAINER_TOKEN }}" >> $GITHUB_ENV
            echo "STACK_ID=${{ secrets.DEV_STACK_ID }}" >> $GITHUB_ENV
            echo "ENDPOINT_ID=${{ secrets.DEV_ENDPOINT_ID }}" >> $GITHUB_ENV
          fi

      - name: Debug Secrets (Do not expose sensitive data)
        run: |
          echo "Using Portainer URL: $PORTAINER_URL"
          echo "Using Stack ID: $STACK_ID"
          echo "Using Endpoint ID: $ENDPOINT_ID"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        run: |
          echo "REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Generate Docker tags
        id: docker_tags
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.SHORT_SHA }}-${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          else
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.SHORT_SHA }}-${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ env.tags }}

      - name: Deploy to Portainer
        run: |
          COMPOSE_CONTENT=$(cat docker/docker-compose.yml)
          
          PAYLOAD=$(jq -n \
            --arg name "deploy-stack" \
            --arg compose "$COMPOSE_CONTENT" \
            '{
              Name: $name,
              StackFileContent: $compose
            }')

          # Update existing stack
          echo "Attempting to update stack..."
          RESPONSE=$(curl -k -v -s -o response.json -w "%{http_code}" -X PUT \
            -H "X-API-Key: $PORTAINER_TOKEN" \
            -H "Content-Type: application/json" \
            "$PORTAINER_URL/api/stacks/$STACK_ID?endpointId=$ENDPOINT_ID" \
            -d "$PAYLOAD")
          
          echo "Response code: $RESPONSE"
          echo "Response body:"
          cat response.json
          
          if [[ "$RESPONSE" -ge 200 && "$RESPONSE" -lt 300 ]]; then
            echo "Deployment successful"
          else
            echo "Deployment failed with status code $RESPONSE"
            echo "Full response body:"
            cat response.json
            exit 1
          fi
